server:
  port: 8084


spring:
  application:
    name: spring-cloud-consul-mail
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
         ##注册到consul的服务名称
        service-name: service-mail

  datasource:
      url: jdbc:mysql://localhost:3306/springcloud_serve?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    host: smtp.qq.com
    password: hwebpmzbhfzjbfjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 894259991@qq.com

