server:
  port: 8086


spring:
  application:
    name: spring-cloud-consul-redis
  cloud:
    consul:
      host: 192.168.31.192
      port: 8500
      discovery:
         ##注册到consul的服务名称
        service-name: service-redis

  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_serve?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
#    password: root
    port: 6379
    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
#    cluster:
#      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    jedis:
      pool:
        max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
        min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
        max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出

mybatis:
  mapper-locations: classpath*:mybatis-mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign.hystrix.enabled: true
